env:
  global:
    - GH_USER=${gh_user}
    - GH_PWD=${gh_pwd}
    - GH_TOKEN=${gh_repo}

language: ruby
rvm:
- 2.5.0
script: bundle update && bundle install && bundle exec jekyll build


deploy:
  provider: pages
  cleanup: false
  verbose: true
  token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main

addons:
  apt:
    packages:
    - plantuml
    - graphviz 
