language: ruby
rvm:
- 2.5.0
sudo: false
script: bundle exec jekyll build && bundle exec rake deploy 
addons:
  apt:
    packages:
    - graphviz 
# env:
#   global:
#     secure: zYxg6lXWHVFGZdqwENZncQ