language: ruby
rvm:
- 2.5.0
script: bundle update && bundle install && bundle exec jekyll build

deploy:
  provider: pages
  cleanup: false
  verbose: true
  token: $gh_repo  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main

addons:
  apt:
    packages:
    - plantuml
    - graphviz 
