# Site settings
title: 친슈 Achelous1
url: "https://achelous1_wiki.github.io"
baseurl: ""
description: >
    친슈 블로그

# My information
email: jsdesign1204@gmail.com
author: 친슈
profile: 
twitter_username: 
github_username: Achelous1
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: Achelous1
  shortname: Achelous1
utterances:
  repo: Achelous1/achelous1_wiki.github.io
  issue-term: pathname
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/Achelous1/achelous1_wiki.github.io/blame/master/_wiki"
edit: "https://github.com/Achelous1/achelous1_wiki.github.io/edit/master/_wiki"
issue: "https://github.com/Achelous1/achelous1_wiki.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
